timestamp: '2025-02-02T13:26:42.812769'
joints:
  shoulder_pan:
    max:
      ticks: 3067
      speed: 0
      load: -1
    center:
      ticks: 1703
      speed: 0
      load: 0
    min:
      ticks: 336
      speed: 2328
      load: 0
  shoulder_lift:
    min:
      ticks: 2091
      speed: 0
      load: 0
    center:
      ticks: 943
      speed: 0
      load: 0
    max:
      ticks: 3865
      speed: -1
      load: 0
  elbow_flex:
    min:
      ticks: 3239
      speed: 0
      load: 0
    center:
      ticks: 1152
      speed: 0
      load: 0
    max:
      ticks: 1004
      speed: 50
      load: 0
  wrist_flex:
    min:
      ticks: 3417
      speed: 0
      load: 0
    center:
      ticks: 2255
      speed: -1
      load: 0
    max:
      ticks: 965
      speed: 0
      load: 0
  wrist_roll:
    min:
      ticks: 1302
      speed: 0
      load: 0
    center:
      ticks: 213
      speed: 0
      load: 0
    max:
      ticks: 2564
      speed: 0
      load: -918
  gripper:
    min:
      ticks: 1731
      speed: 0
      load: 0
    center:
      ticks: 2090
      speed: -1
      load: 0
    max:
      ticks: 3248
      speed: 0
      load: 0
